### ISSUE TITLE
Fix package.json for use with npm + Browserify

### ISSUE THREAD

**Issue by tracker1** [soyjavi/QuoJS#133]
The package,json doesn't actually point to a file that exists and can be used with Browserify.

It would be nice to have a `quo.node.js` that is a min/merged output that will set `module.exports = $$` so that it can be used with Browserify.  Then you'd need to update your main/start script in the package.json and publish to npm.

**Comment by mike-engel** [comment]
Should be fixed by just editing the path. The standalone already exports the module, so package.json just needs to point to the right file. #150 should fix this.

**Comment by slorber** [comment]
@soyjavi can you publish this feature to NPM? Because it does not seem to be available yet in 3.0.8?
