### ISSUE TITLE
No conflict method

### ISSUE THREAD

**Issue by colindresj** [soyjavi/QuoJS#138]
I know the original reason for the `$$` global namespace was to prevent clashes with common libraries like jQuery, so I think it might be useful in the same way to have a no conflict method on Quo, so we can prevent all types of conflicts, regardless of the namespace.

Would be happy to submit a PR for this if it's useful.

**Comment by nickirios** [comment]
Magento uses PrototypeJS, which also uses $$. :(

**Comment by soyjavi** [comment]
Nickirios don't worry $$ is a shortcut of Quo... I mean, you can use Quo() like $$()

**Comment by nickirios** [comment]
Oh, great! Thanks!
