### ISSUE TITLE
Tap event not working

### ISSUE THREAD

**Issue by Nitesh001** [soyjavi/QuoJS#145]
Hello,
I downloaded version 3.0.5 and used 'quo.standalone.js' file.
But I found there is no 'tap' event available in this file. Therefore, we can't use it.
But I found there is another event called 'touch' which is serving the same purpose.
Could you please check once?

Thanks,
Nitesh

**Comment by josdejong** [comment]
+1

**Comment by soyjavi** [comment]
"tap" event is deprecated... now just need use "touch" event.

**Comment by josdejong** [comment]
Would be great if you could update the docs accordingly, the [readme](https://github.com/soyjavi/QuoJS/blob/master/README.md) only mentions methods `tap`, `singleTap`, `doubleTap`, `on("tap", ...)`.
