### ISSUE TITLE
Please publish on npm

### ISSUE THREAD

**Issue by josdejong** [soyjavi/QuoJS#148]
Would be great to have quojs published on npm!

I normally just use npm for full stack JavaScript applications.

**Comment by soyjavi** [comment]
My question is ... why you wanna quojs in a NodePackage Manager... QuoJS is a frontend project, any sense for backend projects... right?

**Comment by josdejong** [comment]
Yes, npm is more and more used for (both) front-end and back-end development (also promoted by npm itself http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging). It's a mess if you need multiple package managers for a single project. More and more people have a workflow using just npm for everything (possibly with commonjs modules and browserify).

**Comment by soyjavi** [comment]
Ok, next week I will upgrade QuoJS with NPM Compatibility


—
Javi Jiménez Villar
@soyjavi

**Comment by josdejong** [comment]
Thanks!

**Comment by soyjavi** [comment]
New version 3.0.7 with NPM support https://github.com/soyjavi/QuoJS/commit/755d3d6af0809a38125850bf708cbf2804a76c8d

**Comment by josdejong** [comment]
Thanks, but as far as I can see you haven't yet published quojs on npm? I can't find it on http://npmjs.org
