### ISSUE TITLE
QouJS and Windows Phone

### ISSUE THREAD

**Issue by hosembafer** [soyjavi/QuoJS#157]
I see, this problem have a older issue, and it's not solved https://github.com/soyjavi/QuoJS/issues/97

I have a same problem in my project, and I want to know, when you want to implement Pointer Events API to QuoJS ? Or if you don't need it, let me a know.

Thank you in advance!!!

**Comment by karneaud** [comment]
@psrafo i too am curious about this...Though I think this project maybe abandoned

**Comment by psrafo** [comment]
@karneaud no, project not abandoned. And this is not QuoJS bug, later I will write here details of this problem.

**Comment by karneaud** [comment]
@psrafo 

Thanks for the response. I was beginning to wonder. Are you also responsible for https://github.com/tapquo/appnima.docs 

I have a project that i am interesting in doing and Appnima sounds PERFECT. However, there are concerns ...i sent an email but no response.

**Comment by psrafo** [comment]
Windows Phone WebView by default rendering by IE10 or EdgeHTML's older versions. And those browsers don't support Pointer Events API. For solve this problem, we need make our WP WebView with EdgeHTML's latest version.

No, I am not responsible for that, sorry :)

**Comment by karneaud** [comment]
+1

**Comment by psrafo** [comment]
Your project's problem too in it ? In WebView render core ?

**Comment by karneaud** [comment]
@psrafo Yes. It doesn't work on Lumina 530 Windows Phone 8.1 IE10
