### ISSUE TITLE
Events trigger duplicated callbacks

### ISSUE THREAD

**Issue by marcelaraujo** [soyjavi/QuoJS#32]
I've testing LungoJS and I found an issue on Android 4.X.

In the init method of Lungo.Boot.Events, I put this code

document.addEventListener('touchstart', function(e){
            e.preventDefault();
            console.log('tap');
}, false);

and the response was just one callback call but if I use the QuoJS, the callback is called twice.

lng.dom('body').tap(function(){
            console.log('tap');
});

**Comment by bsodmike** [comment]
Same here, on `swipeDown`... any thoughts?
