### ISSUE TITLE
IE10 problem

### ISSUE THREAD

**Issue by miladrasooli** [soyjavi/QuoJS#57]
Hi,
When I open my website with IE10 it starts giving 
"Object doesn't support property or method 'ready' "
I can't figure out what the problem is. I need this library very much. 
Please fix this issue.
thanks

**Comment by oliverseal** [comment]
So the suggested fix for this is to block users of IE10? Because this script doesn't just "not work" on IE10 -- it *stops page loading* making it useless for responsive development.

**Comment by soyjavi** [comment]
QuoJS is a Library for Mobile Devices, for now I can't get a good experience in WP devices with QuoJS.
